// COCKPIT TOOL 2 — Internal link injector.
//   pnpm run links <article-slug>   |   pnpm run links --all
// Builds the hub-spoke link graph with TF-IDF relevance, suggests 3-5 links per
// article as MDX comments (NEVER auto-inserts body text), and writes the full
// graph to data/internal-links.json. Darren accepts/rejects each in PR review.
import { basename } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { listArticleFiles, writeJson } from './lib/fs.js';
import { parseFrontmatter } from './lib/frontmatter.js';
import { buildSimilarity, tokenize, type TfidfDoc } from './lib/tfidf.js';

const MIN_LINKS = 3;
const MAX_LINKS = 5;
const SUGGEST_RE = /\n*\{\/\* LINK SUGGEST:[\s\S]*?\*\/\}\n*/g;

interface Article {
  slug: string;
  path: string;
  title: string;
  hub: string;
  keyword: string;
  body: string;
}

function loadArticles(): Article[] {
  return listArticleFiles().map((path) => {
    const raw = readFileSync(path, 'utf8');
    const { data, body } = parseFrontmatter(raw);
    return {
      slug: basename(path, '.mdx'),
      path,
      title: String(data.title ?? ''),
      hub: String(data.hub ?? ''),
      keyword: String(data.keyword ?? ''),
      body,
    };
  });
}

function pickLinks(target: Article, all: Article[], sim: Map<string, Map<string, number>>): Article[] {
  const scores = sim.get(target.slug) ?? new Map();
  const ranked = all
    .filter((a) => a.slug !== target.slug)
    .map((a) => {
      let score = scores.get(a.slug) ?? 0;
      if (a.hub === target.hub) score += 0.15; // same-hub boost
      return { a, score };
    })
    .sort((x, y) => y.score - x.score);

  const sameHub = ranked.filter((r) => r.a.hub === target.hub).slice(0, 2);
  const crossHub = ranked.filter((r) => r.a.hub !== target.hub).slice(0, 2);
  const merged = [...sameHub, ...crossHub]
    .sort((x, y) => y.score - x.score)
    .slice(0, MAX_LINKS)
    .map((r) => r.a);
  return merged.slice(0, Math.max(MIN_LINKS, merged.length) === 0 ? 0 : merged.length);
}

function injectComment(target: Article, links: Article[]): void {
  const cleaned = target.body.replace(SUGGEST_RE, '\n');
  const suggestions = links
    .map((l) => `  - ${l.title} → /${l.hub}/${l.slug}`)
    .join('\n');
  const block =
    links.length > 0
      ? `\n{/* LINK SUGGEST: accept or delete each in review\n${suggestions}\n*/}\n`
      : '\n';
  const raw = readFileSync(target.path, 'utf8');
  const fmEnd = raw.indexOf('\n---', 3) + 4;
  const fm = raw.slice(0, fmEnd);
  writeFileSync(target.path, `${fm}\n${cleaned.trimStart()}${block}`, 'utf8');
}

function main(): void {
  const arg = process.argv[2];
  const all = loadArticles();
  if (all.length === 0) {
    console.log('No articles found in src/content/articles/.');
    return;
  }

  const docs: TfidfDoc[] = all.map((a) => ({
    id: a.slug,
    tokens: tokenize(`${a.title} ${a.keyword} ${a.keyword} ${a.body}`),
  }));
  const sim = buildSimilarity(docs);

  const targets =
    arg === '--all' || !arg ? all : all.filter((a) => a.slug === arg);
  if (targets.length === 0) {
    console.error(`No article matched "${arg}".`);
    process.exit(1);
  }

  const graph: Record<string, string[]> = {};
  for (const t of targets) {
    const links = pickLinks(t, all, sim);
    graph[t.slug] = links.map((l) => l.slug);
    injectComment(t, links);
    console.log(`✓ ${t.slug}: suggested ${links.length} links (${graph[t.slug].join(', ') || 'none'})`);
  }

  // Merge into the full graph file.
  writeJson('data/internal-links.json', {
    _comment: 'Generated by link-injector. Do not edit by hand.',
    generatedAt: new Date().toISOString(),
    graph: arg === '--all' || !arg ? graph : { ...readGraph(), ...graph },
  });
  console.log(`\n✓ Graph written to data/internal-links.json (${Object.keys(graph).length} updated).\n`);
}

function readGraph(): Record<string, string[]> {
  try {
    const j = JSON.parse(readFileSync(new URL('../data/internal-links.json', import.meta.url), 'utf8'));
    return j.graph ?? {};
  } catch {
    return {};
  }
}

main();
